volumes:
  db: {}

services:
  db:
    image: mariadb:10.6
    container_name: aqs_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=gqlSql
      - MYSQL_USER=mysql
    ports:
      - "3300:3306"
